{{- if .Values.chromadb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chromadb-admin.fullname" . }}-chromadb
  labels:
    {{- include "chromadb-admin.chromadbLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.chromadb.replicaCount }}
  selector:
    matchLabels:
      {{- include "chromadb-admin.chromadbSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chromadb-admin.chromadbLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.chromadb.podSecurityContext | nindent 8 }}
      containers:
        - name: chromadb
          securityContext:
            {{- toYaml .Values.chromadb.securityContext | nindent 12 }}
          image: {{ include "chromadb-admin.chromadbImage" . }}
          imagePullPolicy: {{ .Values.chromadb.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.chromadb.service.targetPort }}
              protocol: TCP
          env:
            - name: CHROMA_SERVER_HOST
              value: {{ .Values.chromadb.config.host | quote }}
            - name: CHROMA_SERVER_HTTP_PORT
              value: {{ .Values.chromadb.config.port | quote }}
            - name: ANONYMIZED_TELEMETRY
              value: {{ .Values.chromadb.config.anonymizedTelemetry | quote }}
          {{- if .Values.chromadb.persistence.enabled }}
          volumeMounts:
            - name: chromadb-storage
              mountPath: /chroma/chroma
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.chromadb.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.chromadb.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.chromadb.resources | nindent 12 }}
      {{- if .Values.chromadb.persistence.enabled }}
      volumes:
        - name: chromadb-storage
          persistentVolumeClaim:
            claimName: {{ include "chromadb-admin.fullname" . }}-chromadb-pvc
      {{- end }}
      {{- with .Values.chromadb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.chromadb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.chromadb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 