{{- if not .Values.chromadbAdmin.config.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chromadb-admin.fullname" . }}-secret
  labels:
    {{- include "chromadb-admin.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ include "chromadb-admin.secretKey" . | b64enc | quote }}
  DATABASE_URL: {{ include "chromadb-admin.databaseUrl" . | b64enc | quote }}
  {{- if .Values.chromadbAdmin.config.chromadbToken }}
  CHROMADB_TOKEN: {{ .Values.chromadbAdmin.config.chromadbToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.chromadbAdmin.config.initialAdmin.enabled }}
  INITIAL_ADMIN_PASSWORD: {{ include "chromadb-admin.initialAdminPassword" . | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | default (randAlphaNum 16) | b64enc | quote }}
  {{- end }}
{{- end }} 