name: Build and Publish Image Artifacts

on:
  push:
    tags: [ 'v*' ]
    paths-ignore:
      - charts/**
      - .github

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Build and push Docker image
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
      image-tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,enable={{is_default_branch}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Notify on completion
  notify:
    runs-on: ubuntu-latest
    needs: [build-image]
    if: always()
    steps:
      - name: Notification
        run: |
          if [[ "${{ needs.build-image.result }}" == "success" ]]; then
            echo "✅ Build and publish of Docker images completed successfully!"
            echo "🚀 Docker image: ${{ needs.build-image.outputs.image-tag }}"
          elif [[ "${{ needs.build-image.result }}" == "success" && "${{ github.event_name }}" == "pull_request" ]]; then
            echo "✅ PR build completed successfully!"
          else
            echo "❌ Build or publish failed!"
            exit 1
          fi 